# Default values for 201chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

keyvaultName: "jessekv"
keyvaultSecretName: "jesseACRToken"
secretName: "secrets-store-creds"
tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"