apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "101chart.fullname" . }}
  labels:
    {{- include "101chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "101chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "101chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.fullImageName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}