apiVersion: batch/v1
kind: Job
metadata:
  name: go-hello-world
spec:
  template:
    spec:
      containers:
      - name: go-hello-world
        image: docker.io/iwangjintianwork/go-hello-world:2.0
      restartPolicy: Never
  backoffLimit: 4