# This is a SecretProviderClass example using service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-acr-test
spec:
  provider: azure
  secretObjects:
  - secretName: credentialforacr
    type: kubernetes.io/dockerconfigjson
    data:
    - objectName: {{ .Values.keyvaultSecretName}}
      key: .dockerconfigjson
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName}}
    objects:  |
      array:
        - |
          objectName: {{ .Values.keyvaultSecretName}}
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.tenantId}}