# This is a SecretProviderClass example using service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-acr-test
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: jesseacrcred
    type: kubernetes.io/dockerconfigjson
    data:
    - objectName: jesseACRToken                    # name of the mounted content to sync. this could be the object name or object alias
      key: .dockerconfigjson
  - secretName: foosecret
    type: Opaque
    data:
    - objectName: jesseACRToken                    # name of the mounted content to sync. this could be the object name or object alias
      key: username
  parameters:
    usePodIdentity: "false"
    keyvaultName: "jessekv"
    objects:  |
      array:
        - |
          objectName: jesseACRToken
          objectType: secret             # object types: secret, key or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47                # The tenant ID of the Azure Key Vault instance